project:
  type: website

website:
  title: "SCZ_manuscript"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

lightbox: true
knitr:
  opts_chunk:
    dev: png
    dev.args: { bg: "transparent" } 
format:
  html:
    theme: yeti
    toc: true
    toc-depth: 5
    fig-width: 15
    fig-height: 9
    fig-format: retina
    embed-resources: false
    self-contained: false
    mermaid-format: png
    mermaid:
      theme: neutral
  typst: 
    fontsize: 11pt
    keep-typ: false
    toc: true
    toc-depth: 5
    fig-width: 17
    fig-height: 10
    code-annotations: false
    fig-cap-location: bottom
    tbl-cap-location: top
    papersize: a4
    mermaid-format: png
    margin:
      x: 2cm
      y: 1cm
    columns: 1
    geometry:
      - top=0mm
      - left=0mm
      - right=0mm
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
code-fold: true
code-line-numbers: false
self-contained: true
code-tools: 
  source: true
  toggle: false
code-link: true
code-block-bg: false
code-block-border-left: "#31BAE9"
highlight-style: arrow
execute: 
  warning: false
  freeze: false
  echo: false
crossref:
  fig-prefix: S_Figure   # (default is "Figure")
  fig-title: S_Figure    # (default is "Figure")
  tbl-title: S_Table
  tbl-prefix: S_Table